=== 707090/AxisAndAllies/xml/schema/Map.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema 
	xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="model/untransformed/map"
	xmlns="model/untransformed/map"
	xmlns:cmn="model/untransformed/common"
	xmlns:pct="model/untransformed/placement"
	elementFormDefault="qualified">

	<xs:import schemaLocation="Common.xsd" namespace="model/untransformed/common" />
	
	<xs:element name="map_type">
		
        <xs:complexType>
			<xs:sequence>
				<xs:element name="territory" type="territory_type" maxOccurs="unbounded" />
				<xs:element name="sea_zone" type="sea_zone_type" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
        
        <xs:key name="area_id">
            <xs:selector xpath="territory" />
            <xs:field xpath="id" />
        </xs:key>
        
        <xs:keyref name="area_connections" refer="area_id">
            <xs:selector xpath="territory/connection | sea_zone/connection" />
            <xs:field xpath="." />
        </xs:keyref>
    </xs:element>
        
	<xs:complexType name="area_type">
		<xs:sequence>
			<xs:element name="connection" type="xs:int" minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
		<xs:attribute name="id" type="xs:int" />
	</xs:complexType>
	
	<xs:complexType name="territory_type">
		<xs:complexContent>
			<xs:extension base="area_type">
				<xs:sequence>
					<xs:element name="name" type="xs:string" />
					<xs:element name="value" type="xs:int" default="0" />
					<xs:element name="default_owner" type="cmn:power_type" default="Neutral" />
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="sea_zone_type">
		<xs:complexContent>
			<xs:extension base="area_type">
				<xs:sequence>
					<xs:element name="zone_number" type="xs:int" />
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

</xs:schema>

=== 707090/AxisAndAllies/xml/Map.xml
<?xml version="1.0" encoding="UTF-8"?>
<map:map_type
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="model/untransformed/map schema/Map.xsd"
	xmlns:map="model/untransformed/map">
	
	<map:territory id="0">
		<map:connection>1</map:connection>
		<map:connection>2</map:connection>
		<map:connection>6</map:connection>
		<map:connection>13</map:connection>
		<map:name>Russia</map:name>
		<map:value>3</map:value>
		<map:default_owner>Soviet Union</map:default_owner>
	</map:territory>
	<map:territory id="1">
		<map:connection>6</map:connection>
		<map:connection>12</map:connection>
		<map:connection>13</map:connection>
		<map:connection>22</map:connection>
		<map:connection>48</map:connection>
		<map:connection>54</map:connection>
		<map:connection>57</map:connection>
		<map:connection>70</map:connection>
		<map:connection>88</map:connection>		
		<map:name>Caucasus</map:name>
		<map:value>2</map:value>
		<map:default_owner>Soviet Union</map:default_owner>
	</map:territory>
	<map:territory id="2">
		<map:connection>3</map:connection>
		<map:connection>6</map:connection>
		<map:connection>13</map:connection>
		<map:connection>74</map:connection>
		<map:name>Archangel</map:name>
		<map:value>1</map:value>
		<map:default_owner>Soviet Union</map:default_owner>
	</map:territory>
	<map:territory id="3">
		<map:connection>9</map:connection>
		<map:connection>10</map:connection>
		<map:connection>13</map:connection>
		<map:connection>74</map:connection>
		<map:connection>75</map:connection>
		<map:name>Karelia</map:name>
		<map:value>1</map:value>
		<map:default_owner>Soviet Union</map:default_owner>
	</map:territory>
	<map:territory id="4">
		<map:connection>5</map:connection>
		<map:connection>6</map:connection>
		<map:connection>37</map:connection>
		<map:connection>63</map:connection>
		<map:connection>115</map:connection>
		<map:connection>117</map:connection>
		<map:name>Siberia</map:name>
		<map:value>0</map:value>
		<map:default_owner>Soviet Union</map:default_owner>
	</map:territory>
	<map:territory id="5">
		<map:connection>117</map:connection>
		<map:name>Soviet Far East</map:name>
		<map:value>0</map:value>
		<map:default_owner>Soviet Union</map:default_owner>
	</map:territory>
	<map:territory id="6">
		<map:connection>54</map:connection>
		<map:connection>63</map:connection>
		<map:name>Urals</map:name>
		<map:value>0</map:value>
		<map:default_owner>Soviet Union</map:default_owner>
	</map:territory>
	<map:territory id="7">
		<map:connection>8</map:connection>
		<map:connection>9</map:connection>
		<map:connection>11</map:connection>
		<map:connection>69</map:connection>
		<map:connection>75</map:connection>
		<map:name>Germany</map:name>
		<map:value>4</map:value>
		<map:default_owner>Germany</map:default_owner>
	</map:territory>
	<map:territory id="8">
		<map:connection>11</map:connection>
		<map:connection>67</map:connection>
		<map:connection>69</map:connection>
		<map:connection>75</map:connection>
		<map:connection>76</map:connection>
		<map:connection>77</map:connection>
		<map:connection>78</map:connection>
		<map:name>Western Europe</map:name>
		<map:value>3</map:value>
		<map:default_owner>Germany</map:default_owner>
	</map:territory>
	<map:territory id="9">
		<map:connection>11</map:connection>
		<map:connection>12</map:connection>
		<map:connection>13</map:connection>
		<map:connection>70</map:connection>
		<map:connection>75</map:connection>
		<map:connection>88</map:connection>
		<map:name>Eastern Europe</map:name>
		<map:value>1</map:value>
		<map:default_owner>Germany</map:default_owner>
	</map:territory>
	<map:territory id="10">
		<map:connection>68</map:connection>
		<map:connection>73</map:connection>
		<map:connection>75</map:connection>
		<map:connection>76</map:connection>
		<map:name>Norway/Finland</map:name>
		<map:value>1</map:value>
		<map:default_owner>Germany</map:default_owner>
	</map:territory>
	<map:territory id="11">
		<map:connection>69</map:connection>
		<map:connection>70</map:connection>
		<map:connection>86</map:connection>
		<map:connection>87</map:connection>
		<map:name>Southern Europe</map:name>
		<map:value>1</map:value>
		<map:default_owner>Germany</map:default_owner>
	</map:territory>
	<map:territory id="12">
		<map:connection>13</map:connection>
		<map:connection>88</map:connection>
		<map:name>Ukraine</map:name>
		<map:value>1</map:value>
		<map:default_owner>Germany</map:default_owner>
	</map:territory>
	<map:territory id="13">
		<map:name>West Russia</map:name>
		<map:value>1</map:value>
		<map:default_owner>Germany</map:default_owner>
	</map:territory>
	<map:territory id="14">
		<map:connection>17</map:connection>
		<map:connection>65</map:connection>
		<map:connection>84</map:connection>
		<map:connection>85</map:connection>
		<map:connection>86</map:connection>
		<map:name>North Africa</map:name>
		<map:value>0</map:value>
		<map:default_owner>Germany</map:default_owner>
	</map:territory>
	<map:territory id="15">
		<map:connection>61</map:connection>
		<map:connection>76</map:connection>
		<map:connection>77</map:connection>
		<map:connection>78</map:connection>
		<map:name>United Kingdom</map:name>
		<map:value>3</map:value>
		<map:default_owner>United Kingdom</map:default_owner>
	</map:territory>
	<map:territory id="16">
		<map:connection>100</map:connection>
		<map:name>East Indies</map:name>
		<map:value>2</map:value>
		<map:default_owner>United Kingdom</map:default_owner>
	</map:territory>
	<map:territory id="17">
		<map:connection>22</map:connection>
		<map:connection>24</map:connection>
		<map:connection>25</map:connection>
		<map:connection>30</map:connection>
		<map:connection>65</map:connection>
		<map:connection>87</map:connection>
		<map:connection>98</map:connection>
		<map:name>Anglo-Egypt Sudan</map:name>
		<map:value>1</map:value>
		<map:default_owner>United Kingdom</map:default_owner>
	</map:territory>
	<map:territory id="18">
		<map:connection>103</map:connection>
		<map:name>Australia</map:name>
		<map:value>1</map:value>
		<map:default_owner>United Kingdom</map:default_owner>
	</map:territory>
	<map:territory id="19">
		<map:connection>102</map:connection>
		<map:name>Borneo</map:name>
		<map:value>1</map:value>
		<map:default_owner>United Kingdom</map:default_owner>
	</map:territory>
	<map:territory id="20">
		<map:connection>34</map:connection>
		<map:connection>42</map:connection>
		<map:connection>71</map:connection>
		<map:connection>80</map:connection>
		<map:name>Eastern Canada</map:name>
		<map:value>1</map:value>
		<map:default_owner>United Kingdom</map:default_owner>
	</map:territory>
	<map:territory id="21">
		<map:connection>22</map:connection>
		<map:connection>38</map:connection>
		<map:connection>57</map:connection>
		<map:connection>62</map:connection>
		<map:connection>99</map:connection>
		<map:name>India</map:name>
		<map:value>1</map:value>
		<map:default_owner>United Kingdom</map:default_owner>
	</map:territory>
	<map:territory id="22">
		<map:connection>57</map:connection>
		<map:connection>66</map:connection>
		<map:connection>70</map:connection>
		<map:connection>87</map:connection>
		<map:connection>88</map:connection>
		<map:connection>98</map:connection>
		<map:name>Middle East</map:name>
		<map:value>1</map:value>
		<map:default_owner>United Kingdom</map:default_owner>
	</map:territory>
	<map:territory id="23">
		<map:connection>24</map:connection>
		<map:connection>58</map:connection>
		<map:connection>64</map:connection>
		<map:connection>96</map:connection>
		<map:connection>97</map:connection>
		<map:name>Union of South Africa</map:name>
		<map:value>1</map:value>
		<map:default_owner>United Kingdom</map:default_owner>
	</map:territory>
	<map:territory id="24">
		<map:connection>25</map:connection>
		<map:connection>30</map:connection>
		<map:connection>58</map:connection>
		<map:connection>64</map:connection>
		<map:connection>95</map:connection>
		<map:connection>97</map:connection>
		<map:name>Belgian Congo/Kenya</map:name>
		<map:value>0</map:value>
		<map:default_owner>United Kingdom</map:default_owner>
	</map:territory>
	<map:territory id="25">
		<map:connection>27</map:connection>
		<map:connection>65</map:connection>
		<map:connection>95</map:connection>
		<map:name>French Equitorial Africa</map:name>
		<map:value>0</map:value>
		<map:default_owner>United Kingdom</map:default_owner>
	</map:territory>
	<map:territory id="26">
		<map:connection>97</map:connection>
		<map:name>French Madagascar</map:name>
		<map:value>0</map:value>
		<map:default_owner>United Kingdom</map:default_owner>
	</map:territory>
	<map:territory id="27">
		<map:connection>65</map:connection>
		<map:connection>93</map:connection>
		<map:name>French West Africa</map:name>
		<map:value>0</map:value>
		<map:default_owner>United Kingdom</map:default_owner>
	</map:territory>
	<map:territory id="28">
		<map:connection>67</map:connection>
		<map:connection>84</map:connection>
		<map:connection>85</map:connection>
		<map:name>Gibralter</map:name>
		<map:value>0</map:value>
		<map:default_owner>United Kingdom</map:default_owner>
	</map:territory>
	<map:territory id="29">
		<map:connection>73</map:connection>
		<map:name>Iceland</map:name>
		<map:value>0</map:value>
		<map:default_owner>United Kingdom</map:default_owner>
	</map:territory>
	<map:territory id="30">
		<map:connection>98</map:connection>
		<map:name>Italian East Africa</map:name>
		<map:value>0</map:value>
		<map:default_owner>United Kingdom</map:default_owner>
	</map:territory>
	<map:territory id="31">
		<map:connection>107</map:connection>
		<map:name>New Guinea</map:name>
		<map:value>0</map:value>
		<map:default_owner>United Kingdom</map:default_owner>
	</map:territory>
	<map:territory id="32">
		<map:connection>104</map:connection>
		<map:name>New Zealand</map:name>
		<map:value>0</map:value>
		<map:default_owner>United Kingdom</map:default_owner>
	</map:territory>
	<map:territory id="33">
		<map:connection>107</map:connection>
