=== 707090/AxisAndAllies/xml/schema/Placement.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema 
	xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="model/untransformed/placement"
	xmlns="model/untransformed/placement"
	xmlns:cmn="model/untransformed/common"
	elementFormDefault="qualified">
	
	<xs:import schemaLocation="Common.xsd" namespace="model/untransformed/common" />
	
	<xs:element name="placement_type">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="military_presence" type="military_presence_type" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:complexType name="military_presence_type">
		<xs:sequence>
			<xs:element name="area_ref" type="xs:int"/>
			<xs:element name="military_installment" type="military_installment_type" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="military_installment_type">
		<xs:sequence>
			<xs:element name="owner" type="cmn:power_type" />
			<xs:element name="troop_group" type="troop_group_type" minOccurs="1" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="troop_group_type">
		<xs:sequence>
			<xs:element name="size" type="xs:int"/>
		</xs:sequence>
		<xs:attribute name="type" type="cmn:military_unit_type" use="required" />
	</xs:complexType>
	
	<xs:complexType name="transport_cargo_type">
		<xs:complexContent>
			<xs:extension base="troop_group_type">
				<xs:sequence>
					<xs:element name="cargo" type="military_installment_type" minOccurs="0" maxOccurs="2"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	
</xs:schema>

=== 707090/AxisAndAllies/xml/Placement.xml
<?xml version="1.0" encoding="UTF-8"?>
<pct:placement_type
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="model/untransformed/placement schema/Placement.xsd" 
	xmlns:pct="model/untransformed/placement"
	xmlns:map="model/untransformed/map" 
	xmlns:cmn="model/untransformed/common">
	
	<pct:military_presence>
		<pct:area_ref>0</pct:area_ref>
		<pct:military_installment>
			<pct:owner>Soviet Union</pct:owner>
			<pct:troop_group type="Infantry">
				<pct:size>6</pct:size>
			</pct:troop_group>
			<pct:troop_group type="Tank">
				<pct:size>1</pct:size>
			</pct:troop_group>
			<pct:troop_group type="Fighter">
				<pct:size>1</pct:size>
			</pct:troop_group>
		</pct:military_installment>
	</pct:military_presence>
	<pct:military_presence>
		<pct:area_ref>1</pct:area_ref>
		<pct:military_installment>
			<pct:owner>Soviet Union</pct:owner>
			<pct:troop_group type="Infantry">
				<pct:size>3</pct:size>
			</pct:troop_group>
			<pct:troop_group type="Tank">
				<pct:size>1</pct:size>
			</pct:troop_group>
		</pct:military_installment>
	</pct:military_presence>
	<pct:military_presence>
		<pct:area_ref>2</pct:area_ref>
		<pct:military_installment>
			<pct:owner>Soviet Union</pct:owner>
			<pct:troop_group type="Infantry">
				<pct:size>3</pct:size>
			</pct:troop_group>
		</pct:military_installment>
	</pct:military_presence>
	<pct:military_presence>
		<pct:area_ref>3</pct:area_ref>
		<pct:military_installment>
			<pct:owner>Soviet Union</pct:owner>
			<pct:troop_group type="Infantry">
				<pct:size>3</pct:size>
			</pct:troop_group>
		</pct:military_installment>
	</pct:military_presence>
	<pct:military_presence>
		<pct:area_ref>4</pct:area_ref>
		<pct:military_installment>
			<pct:owner>Soviet Union</pct:owner>
			<pct:troop_group type="Infantry">
				<pct:size>3</pct:size>
			</pct:troop_group>
		</pct:military_installment>
	</pct:military_presence>
	<pct:military_presence>
		<pct:area_ref>7</pct:area_ref>
		<pct:military_installment>
			<pct:owner>Germany</pct:owner>
			<pct:troop_group type="Infantry">
				<pct:size>3</pct:size>
			</pct:troop_group>
			<pct:troop_group type="Fighter">
				<pct:size>1</pct:size>
			</pct:troop_group>
			<pct:troop_group type="Bomber">
				<pct:size>1</pct:size>
			</pct:troop_group>
		</pct:military_installment>
	</pct:military_presence>
	<pct:military_presence>
		<pct:area_ref>8</pct:area_ref>
		<pct:military_installment>
			<pct:owner>Germany</pct:owner>
			<pct:troop_group type="Infantry">
				<pct:size>2</pct:size>
			</pct:troop_group>
			<pct:troop_group type="Tank">
				<pct:size>1</pct:size>
			</pct:troop_group>
			<pct:troop_group type="Fighter">
				<pct:size>1</pct:size>
			</pct:troop_group>
		</pct:military_installment>
	</pct:military_presence>
	<pct:military_presence>
		<pct:area_ref>9</pct:area_ref>
		<pct:military_installment>
			<pct:owner>Germany</pct:owner>
			<pct:troop_group type="Infantry">
				<pct:size>4</pct:size>
			</pct:troop_group>
			<pct:troop_group type="Tank">
				<pct:size>2</pct:size>
			</pct:troop_group>
		</pct:military_installment>
	</pct:military_presence>
	<pct:military_presence>
		<pct:area_ref>10</pct:area_ref>
		<pct:military_installment>
			<pct:owner>Germany</pct:owner>
			<pct:troop_group type="Infantry">
				<pct:size>2</pct:size>
			</pct:troop_group>
		</pct:military_installment>
	</pct:military_presence>
	<pct:military_presence>
		<pct:area_ref>11</pct:area_ref>
		<pct:military_installment>
			<pct:owner>Germany</pct:owner>
			<pct:troop_group type="Infantry">
				<pct:size>2</pct:size>
			</pct:troop_group>
			<pct:troop_group type="Fighter">
				<pct:size>1</pct:size>
			</pct:troop_group>
		</pct:military_installment>
	</pct:military_presence>
	<pct:military_presence>
		<pct:area_ref>12</pct:area_ref>
		<pct:military_installment>
			<pct:owner>Germany</pct:owner>
			<pct:troop_group type="Infantry">
				<pct:size>2</pct:size>
			</pct:troop_group>
			<pct:troop_group type="Tank">
				<pct:size>2</pct:size>
			</pct:troop_group>
		</pct:military_installment>
	</pct:military_presence>
	<pct:military_presence>
		<pct:area_ref>13</pct:area_ref>
		<pct:military_installment>
			<pct:owner>Germany</pct:owner>
			<pct:troop_group type="Infantry">
				<pct:size>3</pct:size>
			</pct:troop_group>
		</pct:military_installment>
	</pct:military_presence>
	<pct:military_presence>
		<pct:area_ref>14</pct:area_ref>
		<pct:military_installment>
			<pct:owner>Germany</pct:owner>
			<pct:troop_group type="Tank">
				<pct:size>1</pct:size>
			</pct:troop_group>
		</pct:military_installment>
	</pct:military_presence>
	<pct:military_presence>
		<pct:area_ref>15</pct:area_ref>
		<pct:military_installment>
			<pct:owner>United Kingdom</pct:owner>
			<pct:troop_group type="Infantry">
				<pct:size>1</pct:size>
			</pct:troop_group>
			<pct:troop_group type="Fighter">
				<pct:size>1</pct:size>
			</pct:troop_group>
			<pct:troop_group type="Bomber">
				<pct:size>1</pct:size>
			</pct:troop_group>
		</pct:military_installment>
	</pct:military_presence>
	<pct:military_presence>
		<pct:area_ref>17</pct:area_ref>
		<pct:military_installment>
			<pct:owner>United Kingdom</pct:owner>
			<pct:troop_group type="Infantry">
				<pct:size>2</pct:size>
			</pct:troop_group>
			<pct:troop_group type="Tank">
				<pct:size>1</pct:size>
			</pct:troop_group>
		</pct:military_installment>
	</pct:military_presence>
	<pct:military_presence>
		<pct:area_ref>18</pct:area_ref>
		<pct:military_installment>
			<pct:owner>United Kingdom</pct:owner>
			<pct:troop_group type="Infantry">
				<pct:size>1</pct:size>
			</pct:troop_group>
		</pct:military_installment>
	</pct:military_presence>
	<pct:military_presence>
		<pct:area_ref>19</pct:area_ref>
		<pct:military_installment>
			<pct:owner>United Kingdom</pct:owner>
			<pct:troop_group type="Tank">
				<pct:size>1</pct:size>
			</pct:troop_group>
		</pct:military_installment>
	</pct:military_presence>
	<pct:military_presence>
		<pct:area_ref>20</pct:area_ref>
		<pct:military_installment>
			<pct:owner>United Kingdom</pct:owner>
			<pct:troop_group type="Infantry">
				<pct:size>2</pct:size>
			</pct:troop_group>
			<pct:troop_group type="Fighter">
				<pct:size>1</pct:size>
			</pct:troop_group>
		</pct:military_installment>
	</pct:military_presence>
	<pct:military_presence>
		<pct:area_ref>21</pct:area_ref>
		<pct:military_installment>
			<pct:owner>United Kingdom</pct:owner>
			<pct:troop_group type="Infantry">
				<pct:size>1</pct:size>
			</pct:troop_group>
		</pct:military_installment>
	</pct:military_presence>
	<pct:military_presence>
		<pct:area_ref>22</pct:area_ref>
		<pct:military_installment>
			<pct:owner>Japan</pct:owner>
			<pct:troop_group type="Infantry">
				<pct:size>4</pct:size>
			</pct:troop_group>
			<pct:troop_group type="Tank">
				<pct:size>1</pct:size>
			</pct:troop_group>
			<pct:troop_group type="Fighter">
				<pct:size>1</pct:size>
			</pct:troop_group>
			<pct:troop_group type="Bomber">
				<pct:size>1</pct:size>
			</pct:troop_group>
		</pct:military_installment>
	</pct:military_presence>
	<pct:military_presence>
		<pct:area_ref>23</pct:area_ref>
		<pct:military_installment>
			<pct:owner>Japan</pct:owner>
			<pct:troop_group type="Infantry">
				<pct:size>2</pct:size>
			</pct:troop_group>
		</pct:military_installment>
	</pct:military_presence>
	<pct:military_presence>
		<pct:area_ref>24</pct:area_ref>
		<pct:military_installment>
			<pct:owner>Japan</pct:owner>
			<pct:troop_group type="Infantry">
				<pct:size>2</pct:size>
			</pct:troop_group>
		</pct:military_installment>
	</pct:military_presence>
	<pct:military_presence>
		<pct:area_ref>25</pct:area_ref>
		<pct:military_installment>
			<pct:owner>Japan</pct:owner>
			<pct:troop_group type="Infantry">
				<pct:size>2</pct:size>
			</pct:troop_group>
		</pct:military_installment>
	</pct:military_presence>
	<pct:military_presence>
		<pct:area_ref>26</pct:area_ref>
		<pct:military_installment>
			<pct:owner>United States</pct:owner>
			<pct:troop_group type="Infantry">
				<pct:size>2</pct:size>
			</pct:troop_group>
			<pct:troop_group type="Tank">
				<pct:size>1</pct:size>
			</pct:troop_group>
			<pct:troop_group type="Fighter">
				<pct:size>1</pct:size>
			</pct:troop_group>
			<pct:troop_group type="Bomber">
				<pct:size>1</pct:size>
			</pct:troop_group>
		</pct:military_installment>
	</pct:military_presence>
	<pct:military_presence>
		<pct:area_ref>27</pct:area_ref>
		<pct:military_installment>
			<pct:owner>United States</pct:owner>
			<pct:troop_group type="Infantry">
				<pct:size>2</pct:size>
			</pct:troop_group>
			<pct:troop_group type="Tank">
				<pct:size>1</pct:size>
			</pct:troop_group>
		</pct:military_installment>
	</pct:military_presence>
	<pct:military_presence>
		<pct:area_ref>28</pct:area_ref>
		<pct:military_installment>
			<pct:owner>United States</pct:owner>
			<pct:troop_group type="Infantry">
				<pct:size>1</pct:size>
			</pct:troop_group>
		</pct:military_installment>
	</pct:military_presence>
	<pct:military_presence>
		<pct:area_ref>29</pct:area_ref>
		<pct:military_installment>
			<pct:owner>United States</pct:owner>
			<pct:troop_group type="Infantry">
				<pct:size>1</pct:size>
			</pct:troop_group>
		</pct:military_installment>
	</pct:military_presence>
	<pct:military_presence>
		<pct:area_ref>30</pct:area_ref>
		<pct:military_installment>
			<pct:owner>United States</pct:owner>
			<pct:troop_group type="Infantry">
				<pct:size>2</pct:size>
			</pct:troop_group>
		</pct:military_installment>
	</pct:military_presence>
	<pct:military_presence>
		<pct:area_ref>31</pct:area_ref>
		<pct:military_installment>
			<pct:owner>United States</pct:owner>
			<pct:troop_group type="Infantry">
				<pct:size>1</pct:size>
			</pct:troop_group>
		</pct:military_installment>
	</pct:military_presence>
	<pct:military_presence>
		<pct:area_ref>32</pct:area_ref>
		<pct:military_installment>
			<pct:owner>Soviet Union</pct:owner>
			<pct:troop_group type="Submarine">
				<pct:size>1</pct:size>
